# Generated by Django 6.1.1 on 2026-09-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='pic_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
